[workspace]
members = ["aya-example-lsm", "aya-example-lsm-common", "xtask"]

[patch.crates-io]
aya = { git = "https://github.com/vadorovsky/aya", branch = "lsm" }
# aya = { path = "../../aya/bpf/aya-bpf" }
