[package]
name = "aya-example-lsm-common"
version = "0.1.0"
edition = "2018"

[features]
default = []
userspace = [ "aya" ]

[dependencies]
aya = { git = "https://github.com/vadorovsky/aya", branch="lsm", optional=true }
# aya = { path = "../../aya/aya", optional=true }

[lib]
path = "src/lib.rs"
